### ISSUE TITLE
Route tracy.bar not defined when Tracy is enabled and bar is not shown, causing error

### ISSUE THREAD

**Issue by rootpd** [recca0120/laravel-tracy#48]
When the `showBar` config option is set to `false`, no web routes are registered - including `tracy.bar` route. However Tracy attempts to use that route in `DebuggerManager` when the error occurs. 

As the route is not defined unless bar was shown, it's causing errors and the Exception handler not being rendered properly.

`php artisan route:clear` was attempted and did not helped (as it's not related to the route cache).

Set up your `config/tracy.php` with this options:

```php
return [
    // ...
    'enabled' => true,
    'showBar' => false,
    // ...
];
```

And generate some notice within the code:

```php
$noArr = null;
foreach ($noArr as $foo) {}
```

See the call stack it triggers:

```
[2019-03-13 08:47:22] production.ERROR: Uncaught InvalidArgumentException: Route [tracy.bar] not defined. in /var/www/html/Campaign/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:389
Stack trace:
#0 /var/www/html/Campaign/vendor/recca0120/laravel-tracy/src/DebuggerManager.php(322): Illuminate\Routing\UrlGenerator->route('tracy.bar')
#1 /var/www/html/Campaign/vendor/recca0120/laravel-tracy/src/DebuggerManager.php(307): Recca0120\LaravelTracy\DebuggerManager->replacePath('<!DOCTYPE html>...')
#2 /var/www/html/Campaign/vendor/recca0120/laravel-tracy/src/DebuggerManager.php(232): Recca0120\LaravelTracy\DebuggerManager->renderBuffer(Object(Closure))
#3 /var/www/html/Campaign/vendor/recca0120/laravel-tracy/src/Exceptions/Handler.php(65): Recca0120\LaravelTracy\DebuggerManager->exceptionHandler(Object(InvalidArgumentException))
#4 /var/www/html/Campaign/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(112): Recca0120\LaravelTracy\Exceptions\Handler->render(Object(App\Http\Request), Object(InvalidArgumentE {"userId":1,"email":"dulacka@gmail.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Uncaught InvalidArgumentException: Route [tracy.bar] not defined. in /var/www/html/Campaign/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:389
Stack trace:
#0 /var/www/html/Campaign/vendor/recca0120/laravel-tracy/src/DebuggerManager.php(322): Illuminate\\Routing\\UrlGenerator->route('tracy.bar')
#1 /var/www/html/Campaign/vendor/recca0120/laravel-tracy/src/DebuggerManager.php(307): Recca0120\\LaravelTracy\\DebuggerManager->replacePath('<!DOCTYPE html>...')
#2 /var/www/html/Campaign/vendor/recca0120/laravel-tracy/src/DebuggerManager.php(232): Recca0120\\LaravelTracy\\DebuggerManager->renderBuffer(Object(Closure))
#3 /var/www/html/Campaign/vendor/recca0120/laravel-tracy/src/Exceptions/Handler.php(65): Recca0120\\LaravelTracy\\DebuggerManager->exceptionHandler(Object(InvalidArgumentException))
#4 /var/www/html/Campaign/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(112): Recca0120\\LaravelTracy\\Exceptions\\Handler->render(Object(App\\Http\\Request), Object(InvalidArgumentE at /var/www/html/Campaign/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:389)
[stacktrace]
#0 /var/www/html/Campaign/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(137): Symfony\\Component\\Debug\\Exception\\FatalErrorException->__construct()
#1 /var/www/html/Campaign/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->fatalExceptionFromError()
#2 /var/www/html/Campaign/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()
#3 {main}
"} 
```

**Comment by recca0120** [comment]
this is a bug, 
when app run in console, 
it will not register any routes.
when you run artisan route:cache, it will be failed.

try to update to pass this bug XD

**Comment by rootpd** [comment]
Hi, thanks for the bugfix. Updating the library (`v1.8.20 => v1.8.23`) fixed the issue.
